/r/abb_egm_hardware_sim:
  ros__parameters:
    start_position:
      joints:
        - yumi_joint_1_r
        - yumi_joint_2_r
        - yumi_joint_7_r
        - yumi_joint_3_r
        - yumi_joint_4_r
        - yumi_joint_5_r
        - yumi_joint_6_r
      values:
        - 0.0
        - -2.2689
        - -2.3562
        - 0.5235
        - 0.0
        - 0.5235
        - 0.0



      