yumi:
  port: 6512
  joints: 
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r

  joint_position_controller:
    type:   "ros_controllers::JointPositionController"
    joints: 
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r
    pid: {p: 1.2, i: 0, d: 0 , i_min: -4, i_max: 4, antiwindup: True}
    